### ISSUE TITLE
📣 Breaking Changes to the MetaMask Provider are Here 

### ISSUE THREAD

**Issue by tesla809** [SwipeWallet/venus-protocol#11]
### 📣 Breaking Changes to the MetaMask Provider are Here 

Hi there 👋

Is your website or dapp connecting to MetaMask? 

The MetaMask team is currently in the process of shipping a breaking change. 

Soon, MetaMask will stop injecting window.web3 and make a limited number of breaking changes to our window.ethereum API. To see what's changing and learn what to do next, please head to the [MetaMask Ethereum Provider migration guide](https://docs.metamask.io/guide/provider-migration.html#table-of-contents).

We've provided greater detail about what's changing and why in [our latest blog post](https://medium.com/@taliaknowles/7b11c9388be9) and [our prior blog post](https://medium.com/metamask/breaking-changes-to-the-metamask-provider-its-happening-eebc91fff1a7).

Currently, we're past the deprecation period (which started November 16th, 2020) and plan to release this update within the coming week.

This email is a friendly last reminder to please make sure your codebase is updated. If you're unsure about what to do next, we recommend forwarding this email to your development team.

If you have questions or need a little help, you can message me directly, message support@metamask.io or head to [this GitHub issue](https://github.com/MetaMask/metamask-extension/issues/8077), and we'll do our very best to help you out.

Thanks,
Anthony Albertorio
Community Builder / Developer Relations
ConsenSys | MetaMask

**Comment by gryincent** [comment]
Hi Anthony,
Already handled with metamask migration in venus protocol

Thanks for your information
