### ISSUE TITLE
curious about the contract coding

### ISSUE THREAD

**Issue by guagualvcha** [SwipeWallet/venus-protocol#14]
```
    function mint(uint mintAmount) external returns (uint) {
        mintAmount; // Shh
        delegateAndReturn();
    }
```

Why `mintAmount` here? What's the meaning of `Shh`

**Comment by passiondev11** [comment]
`mintAmount` is used to remove warnings.
there is `mintAmount` for future use.

**Comment by brightdev33** [comment]
`mintAmount` is for future use.
there is command to remove compile warning and to show that it will be used in the future.
