### ISSUE TITLE
Calculating Supply Venus Apy

### ISSUE THREAD

**Issue by modvili** [SwipeWallet/venus-protocol#15]
Hi,

What is the formula for calculating the supply and borrow Venus APY for each market (vToken)?

The formula which I found in the docs does only calculate the  supply Apy and borrow Apy of the vToken but not incl. the XVS APY.

Thank you!

**Comment by gryincent** [comment]
```
const underlyingDecimals = vTokenToGetVenusApy.underlying.decimal;
const vTokenDecimals = 8; // always 8
const comptroller;
const vToken;
const apxBlockSpeedInSeconds = 3;

  let venusSpeed = comptroller.venusSpeeds(vToken);
  let xvsPrice = need to get xvsPrice in oracle;
  let totalBorrows = vToken.totalBorrowsCurrent();
  let totalSupply = vToken.totalSupply();
  let exchangeRate = vToken.exchangeRateCurrent();

  // Total supply needs to be converted from vTokens
  const mantissa = 18 + parseInt(underlyingDecimals) - vTokenDecimals;
  exchangeRate = +exchangeRate.toString() / Math.pow(10, mantissa);

  venusSpeed = venusSpeed / 1e18; // XVS has 18 decimal places
  venusPrice = venusPrice / 1e18;  // price feed is USD price with 18 decimal places
  totalBorrows = +totalBorrows.toString() / (Math.pow(10, underlyingDecimals));
  totalSupply = (+totalSupply.toString() * exchangeRate) / (Math.pow(10, underlyingDecimals));

  const venusPerDay = venusSpeed * parseInt((60 * 60 * 24) / apxBlockSpeedInSeconds);

  const venusBorrowApy = 100 * (Math.pow((1 + (venusPrice * venusPerDay / totalBorrows)), 365) - 1);
  const venusSupplyApy = 100 * (Math.pow((1 + (venusPrice * venusPerDay / totalSupply)), 365) - 1);

  console.log('Venus Borrow APY %:', venusBorrowApy);
  console.log(Venus Supply APY %:', venusSupplyApy);
```
Please refere this code

**Comment by modvili** [comment]
This is very helpfull. Thenk you so much!

**Comment by modvili** [comment]
Hi again, 

I tried the provided code but the results are wrong. 
For example, with the above code and provinded information I get the following results for vBNB:

--- original values---
underlyingDecimals: 18
vTokenDecimals: 8
venusSpeed: 69519724574177580
venusPrice: 3800000000000000000
totalBorrows: 785300312406861362380971
totalSupply: 8984766586860885
exchangeRate: 200127276431430868798509334
------calculation----
totalSupplyTimesExchangeRate: 0.00017980968664005922
venusPerDay: 2002.1680677363145
**venusBorrowApy: 3275.793821046289**
**venusSupplyApy: Infinity**

Expected result (based on https://api.venus.io/api/governance/venus) should be:
"venusBorrowApy": "13.40595320365917853",
"venusSupplyApy": "5.648654352585174061"

I must be doing something wrong, I just dont know what.
I would really appreciate if you could have a look at it.

**Comment by pmprete** [comment]
This was very helpful, one small comment is that the actual formula is
```js
underlyingPrice = underlyingPrice / 1e18;  // price feed of the underlyingToken in USD with 18 decimal places

const venusBorrowApy = 100 * (Math.pow((1 + (venusPrice * venusPerDay / (totalBorrows * underlyingPrice)), 365) - 1);
```
