### ISSUE TITLE
How to get total VAI minted and amount of borrowers and suppliers

### ISSUE THREAD

**Issue by xin866** [SwipeWallet/venus-protocol#17]
Hi,

Can you please tell me how I can get the total VAI mintend directly from the smart contract?

And also would like to know how I can read the the total borrowers and suppliers from the smart contract.

**Comment by gryincent** [comment]
you can get total VAI minted amount from VAI contract as total supply.
and for total borrowers and suppliers, you should get from venus api
please check this doc
https://docs.venus.io

**Comment by xin866** [comment]
Thank you!
