### ISSUE TITLE
PLEASE HELP - LOSS OF FUNDS TO CONTRACT ADDRESS - 0x08fb41e8b54b24c6ce3ea18ee592d64039cfadbf69f03c48f6b8ee9d1f42304f

### ISSUE THREAD

**Issue by tylerleec** [SwipeWallet/venus-protocol#2]
Hello, I am in need of some help dearly. I received an airdrop for XVS coins staking on Pancakeswap. I was trying to move my XVS funds to Binance but accidentally sent it to the XVS CONTRACT ADDRESS after adding that token address to my Metamask. You can see my transaction of 165.6499 XVS tokens. I am very stressed about this issue and really hoping the funds can be returned to the wallet of origin. I dont have much money $ to spare or can risk losing. I would appreciate some assistance very much! Please help me! Thank you for your time!

https://bscscan.com/tx/0x08fb41e8b54b24c6ce3ea18ee592d64039cfadbf69f03c48f6b8ee9d1f42304f

![IMG_5206](https://user-images.githubusercontent.com/72435018/95170623-a2401000-0769-11eb-8e12-71cbd492fb06.PNG)

**Comment by tylerleec** [comment]
Still no response after 5 days?..... Does anyone even read these issues?

**Comment by karandeepvirk85** [comment]
🤪

**Comment by gryincent** [comment]
For security reason, contract is not allowing to send user wrong send XVS to user address.
