### ISSUE TITLE
RedeemUnderlying does not redeem the entire balance

### ISSUE THREAD

**Issue by xin866** [SwipeWallet/venus-protocol#22]
Hi,

When I call the RedeemUnderlying method to redeem the the max supplied balance, it seems that very small amount of vTokens still stay in the venus protocol. I think that this amount is the interest rate generated from the last block after I called the redeem method.
How can I redeem the supplied tokens incl. the interest so that no more vTokens are left in the venus protocol? (like how the withdrawal of main site works)

Thank you

**Comment by gryincent** [comment]
you can input amount as -1 for full redeem

**Comment by xin866** [comment]
Thank you for your response @gryincent!

When I input -1 and call the method redeemUnderlying I get the following error:

Error: value out-of-bounds (argument="redeemAmount", value="-1", code=INVALID_ARGUMENT, version=abi/5.0.7)

I also tried -0x1 but still get the same error.
